config/routes.rb
Rails.application.routes.draw do

  resources :patients do
    collection do
      get :finished
    end
  end

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root :to => "patients#new", as: :authenticated_root
    end
    unauthenticated :member do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/patient.rb
class Patient < ActiveRecord::Base

  belongs_to :user

  before_save  :update_user

  def update_user
    user = self.user
    if user.last_case.nil?
      user.last_case = 1
      user.save
    else
      user.last_case += 1
      user.save
    end
  end


  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |patient|
        csv << patient.attributes.values_at(*column_names)
      end
    end
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :patients

  def define_case_number
    if self.last_case.blank?
      1
    else
      self.last_case == 1 ? 2 : self.last_case + 1
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  require 'csv'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!, :only => [:index, :new]

  def index
  end


  def new
  end

  def edit
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  before_action :set_patient, only: [:show, :edit, :update, :destroy, :clear]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
    respond_to do |format|
      format.html
      format.csv { send_data @patients.to_csv }
      format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
    @case_number = current_user.define_case_number
    if @case_number == 475
      redirect_to finished_patients_path
    end
    # if Patient.where(:case_number => @case_number - 1).blank?
    #   @previous = nil
    # else
    #   @previous = Patient.where(:case_number => @case_number - 1).first
    # end
  end


  def finished
    render 'finished'
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    respond_to do |format|
      if @patient.save
        format.html { redirect_to new_patient_path}
        format.json { render :new, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:abnormal, :fibrosis, :tbx, :hcying, :gg, :ret, :emph, :user_id, :case_number)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController


# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    # Override Devise default behaviour and create a profile as well
    LoginMailer.notify_admin_login(user).deliver_now
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
    user = current_user
    LoginMailer.notify_admin_login(user).deliver_now
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper


  def full_title(page_title = '')
    base_title = "The Lung Sounds Project"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end


end

app/helpers/devise_helper.rb
module DeviseHelper

  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert label-danger alert-block">
       #{messages}
     </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_footer.html.erb
<div class = "row">
  <div class="col-md-12 col-sm-12 col-xs-12">
  <div class="footer">
    <small>
      Lung Sounds Project Platform by <a href="https://uk.linkedin.com/in/SLFWalsh">Simon Walsh</a>
    </small>
  </div>

  </div>


</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><b>Lung Sounds Project</b></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
        <% else %>
            <li><%= link_to "Login", new_user_session_path  %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <div class ="row">
    <div class="col-md-12 col-sm-12 col-xs-12 Content">

      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}")%>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>

    </div>
  </div>
</div>


</body>
</html>

app/views/patients/_form.html.erb
<%= simple_form_for(@patient) do |f| %>

    <div class = "patterns">
      <div class="field">
        <%= f.check_box :abnormal, :value => 1 %>
        <%= label_tag(:abnormal, "Abnormal - if Yes, check the box, otherwise leave blank") %>
      </div>
    </div>
    <div class = "patterns">
      <div class="field">
        <%= f.check_box :fibrosis, :value => 1, :class => "radio" %>
        <%= label_tag(:age_adult, "Fibrosis - if Yes, check the box, otherwise leave blank") %>
      </div>
    </div>
    <div class = "patterns">
      <div class="field name">
        <b>Traction bronchiectasis</b>
      </div>
      <div class="field">
        <%= f.radio_button :tbx, 1, :class => "radio" %>
        <%= label_tag(:tbx, "Mild") %>
        <%= f.radio_button :tbx, 2, :class => "radio" %>
        <%= label_tag(:tbx, "Moderate") %>
        <%= f.radio_button :tbx, 3, :class => "radio" %>
        <%= label_tag(:tbx, "Severe") %>
      </div>
    </div>
    <div class = "patterns">
      <div class="field name">
        <b>Honeycombing</b>
      </div>
      <div class="field">
        <%= f.radio_button :hcying, 1, :class => "radio" %>
        <%= label_tag(:hcying, "<25%") %>
        <%= f.radio_button :hcying, 2, :class => "radio" %>
        <%= label_tag(:hcying, "25%-50%") %>
        <%= f.radio_button :hcying, 3, :class => "radio" %>
        <%= label_tag(:hcying, "50%-75%") %>
        <%= f.radio_button :hcying, 4, :class => "radio" %>
        <%= label_tag(:hcying, ">75%") %>
      </div>
    </div>
    <div class = "patterns">
      <div class="field name">
        <b>Ground-glass opacification</b>
      </div>
      <div class="field">
        <%= f.radio_button :gg,  1, :class => "radio" %>
        <%= label_tag(:gg, "<25%") %>
        <%= f.radio_button :gg, 2, :class => "radio" %>
        <%= label_tag(:gg, "25%-50%") %>
        <%= f.radio_button :gg,  3, :class => "radio" %>
        <%= label_tag(:gg, "50%-75%") %>
        <%= f.radio_button :gg,  4, :class => "radio" %>
        <%= label_tag(:gg, ">75%") %>
      </div>
    </div>
    <div class = "patterns">
      <div class="field name">
        <b>Reticulation</b>
      </div>
      <div class="field">
        <%= f.radio_button :ret,  1, :class => "radio" %>
        <%= label_tag(:ret, "<25%") %>
        <%= f.radio_button :ret,  2, :class => "radio" %>
        <%= label_tag(:ret, "25%-50%") %>
        <%= f.radio_button :ret,  3, :class => "radio" %>
        <%= label_tag(:ret, "50%-75%") %>
        <%= f.radio_button :ret,  4, :class => "radio" %>
        <%= label_tag(:ret, ">75%") %>
      </div>
    </div>
    <div class = "patterns">
      <div class="field name">
        <b>Emphysema</b>
      </div>
      <div class="field">
        <%= f.radio_button :emph,  1, :class => "radio" %>
        <%= label_tag(:emph, "<25%") %>
        <%= f.radio_button :emph,  2, :class => "radio" %>
        <%= label_tag(:emph, "25%-50%") %>
        <%= f.radio_button :emph,  3, :class => "radio" %>
        <%= label_tag(:emph, "50%-75%") %>
        <%= f.radio_button :emph, 4, :class => "radio" %>
        <%= label_tag(:emph, ">75%") %>
      </div>
    </div>

    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :case_number, :value => @case_number %>
    <div class="btn-group" role="group" aria-label="...">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/finished.html.erb
<h1>Finished!</h1>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>

<table>
  <thead>
    <tr>
      <th>Case</th>
      <th>Abnormal</th>
      <th>Fibrosis</th>
      <th>Tbx</th>
      <th>Hcying</th>
      <th>Gg</th>
      <th>Ret</th>
      <th>Emph</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.case_number %></td>
        <td><%= patient.abnormal %></td>
        <td><%= patient.abnormal %></td>
        <td><%= patient.fibrosis %></td>
        <td><%= patient.tbx %></td>
        <td><%= patient.hcying %></td>
        <td><%= patient.gg %></td>
        <td><%= patient.ret %></td>
        <td><%= patient.emph %></td>
        <td><%= patient.user.email %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

<p>
  Download:
  <%= link_to "CSV", patients_path(format: "csv") %>
</p>

app/views/patients/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="Number">CASE</Data></Cell>
        <Cell><Data ss:Type="Number">ABNORMAL</Data></Cell>
        <Cell><Data ss:Type="Number">FIBROSIS</Data></Cell>
        <Cell><Data ss:Type="Number">TBX</Data></Cell>
        <Cell><Data ss:Type="Number">HCYING</Data></Cell>
        <Cell><Data ss:Type="Number">GGO</Data></Cell>
        <Cell><Data ss:Type="Number">RET</Data></Cell>
        <Cell><Data ss:Type="Number">EMPHY</Data></Cell>
        <Cell><Data ss:Type="Number">USER</Data></Cell>


      </Row>
      <% @patients.each do |patient| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= patient.case_number %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= patient.abnormal %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= patient.fibrosis %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= patient.tbx %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= patient.hcying %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= patient.gg %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= patient.ret %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= patient.emph %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= patient.user.email %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/patients/new.html.erb
<h2>Case number <%= @case_number %></h2>
<ol class="Warning">
  <li>Remember, if you select nothing, it means you are saying <span class ="underline">that</span> abnormality is not present.</li>
  <li>By unselecting the "abnormal" checkbox, you can unselect all other selections.</li>
  <li>The abnormal checkbox will automatically check if you select any pattern and the fibrosis checkbox will automatically check if you select Tbx or Hcying.</li>
</ol>

<div class="col-md-5 col-sm-5 col-xs-12">

    <div class = "ImageHolder">
        <img src="https://s3.amazonaws.com/lungsoundsbucket/<%= @case_number%>.jpg" />
    </div>
</div>
<div class="col-md-7 col-sm-7 col-xs-12">

   <div class = "FormHolder">
    <%= render 'form' %>
   </div>

</div>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Abnormal:</strong>
  <%= @patient.abnormal %>
</p>

<p>
  <strong>Fibrosis:</strong>
  <%= @patient.fibrosis %>
</p>

<p>
  <strong>Tbx:</strong>
  <%= @patient.tbx %>
</p>

<p>
  <strong>Hcying:</strong>
  <%= @patient.hcying %>
</p>

<p>
  <strong>Gg:</strong>
  <%= @patient.gg %>
</p>

<p>
  <strong>Ret:</strong>
  <%= @patient.ret %>
</p>

<p>
  <strong>Emph:</strong>
  <%= @patient.emph %>
</p>

<p>
  <strong>User:</strong>
  <%= @patient.user.email %>
  <%= @patient.user.last_case %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>